import argparse
def setArgs():
    parser = argparse.ArgumentParser()
    parser.add_argument('--numEpochs', type=int, default=50, help='Number of epochs')
    parser.add_argument('--vidLen', type=int, default=32, help='Number of frames in a clip')
    parser.add_argument('--batchSize', type=int, default=4, help='Training batch size')
    parser.add_argument('--resume', help='whether training should resume from the previous checkpoint',action='store_true')
    parser.add_argument('--mode', type=str, default='both', help='model type - both, only_limbs, only_keypoints', choices=['both', 'only_limbs', 'only_keypoints']) 
    parser.add_argument('--dirinp', type=str)
    parser.add_argument('--fusionType', type=str, default='C', help='fusion type - A for add, M for multiply, C for concat', choices=['C','A','M']) 
    parser.add_argument('--savePath', type=str, default='/gdrive/My Drive/THESIS/Data', help='folder path to save the models')
    # parser.add_argument('--rwfPretrainedPath', type=str, default='NOT_SET', help='path to the weights pretrained on rwf dataset')
    parser.add_argument('--resumePath', type=str, default='NOT_SET', help='path to the weights for resuming from previous checkpoint')
    parser.add_argument('--LearningRate', type=float, default=1e-06, help='learning rate to resume training from')
    parser.add_argument('--resumeLearningRate', type=float, default=5e-05, help='learning rate to resume training from')
    parser.add_argument('--HeatMapSize', type=int, default=224, help='Size of 2D heatmap')
    parser.add_argument('--DatasetName', type=str)
    parser.add_argument('--version', type=int, default=0)
    parser.add_argument('--cnnTrainable', type=int)
    # args = parser.parse_args()
    # train(args)
    return parser